language: node_js
node_js:
  - "node"
  - "iojs"

notifications:
  slack: polyglotted:oI752wOHgUY3xWHyCqXRhLs3

before_install:
  - npm i -g codeclimate-test-reporter
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

after_script:
  - CODECLIMATE_REPO_TOKEN=ab8d2d8bae327c09279b05370066c7f27ff8babfddb1c386ba99b022c44d2986 codeclimate < report/jasmine-coverage/lcov.info
